[package]
name = "tracelet"
version = "0.3.0"
edition = "2021"
license = "MIT"

[workspace]
members = ["tracelet-common"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
libbpf-rs = "0.27"
ratatui = "0.30"
crossterm = "0.29"
tracelet-common = { path = "tracelet-common" }

[build-dependencies]
libbpf-cargo = "0.27"
